name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Restore the dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn all
