name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Restore the dependencies
        run: |
            export CONFIG_CLIENT_ID=${{secrets.CONFIG_CLIENT_ID}};
            yarn install --frozen-lockfile
      - name: Build
        run: yarn all
          
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          milliseconds: 1000
