name: Test
on:
  push:
    branches:
      - main
  create:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Create a release draft for a version tag
        id: create-release-draft
        uses: ./
      - name: Print URL of the release draft
        run: echo ${{ steps.create-release-draft.ouputs.release-url}}

