name: Test
on:
  push:
    branches:
      - main
  create:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v2
      - name: Create a release draft for a version tag
        id: create-release-draft
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN}}
      - name: Print URL of the release draft
        run: |      
          echo ${{ github.context}}
          echo ${{ github.context.payload}}      
          echo ${{ steps.create-release-draft.ouputs}}
          echo ${{ steps.create-release-draft.ouputs.release-url}}

